#! /bin/sh

# Hotkey manager
sxhkd &

bspc monitor -d I II III IV V

bspc config border_width    0
bspc config window_gap      20

bspc config split_ratio         0.5
bspc config borderless_monocle	true
bspc config gapless_monocle	    true
bspc config single_monocle      true

bspc config presel_feedback_color   "#617aff"

bspc config top_padding     40

bspc config click_to_focus  any

# dropdown terminal
bspc rule -a scratchpad-terminal layer=above state=floating sticky=on
xrdb -merge ~/.Xresources &

# Compositor
compton -b &

# fix window reparenting issue for Android Studio, IntelliJ, PyCharm, etc.
wmname LG3D

# Desktop background
feh --bg-fill ~/.wallpaper.png &

# System bar
yabar &

# autohide scratchpad on lose focus
$HOME/bin/autohide-scratchpad &

# auto lock on lid close
$HOME/bin/autolock &

# Notification manager
dunst &

# Turn on numlock
numlockx on &

# Set volume at 50
pamixer --set-volume 50 &

# Key customizations
# Menu key = Compose key
# CapsLock = Esc
setxkbmap \
    -option compose:menu \
    -option caps:escape

# Start IBus
ibus-daemon -d &

